server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sports
    username: ana
    password: 2909
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB53Dialect